# Generated by Django 5.0.4 on 2024-09-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='images',
            new_name='product_images',
        ),
    ]
