# Generated by Django 5.0.4 on 2024-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_images_productimages_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='reviewer',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='productreview',
            name='reviewer_image',
            field=models.ImageField(default='reviewer.png', null=True, upload_to='review'),
        ),
    ]
