# Generated by Django 5.0.4 on 2024-09-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productreview_reviewer_productreview_reviewer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='reviewer_image',
            field=models.ImageField(default='reviewer.jpg', upload_to='review'),
        ),
    ]
